version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stonenodes
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - stonenodes-data:/app/backend/data
    env_file:
      - .env

volumes:
  stonenodes-data:
